name: Build macOS Universal Binary

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install setuptools
        run: brew install setuptools

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Ensure this matches your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build renderer process
        run: npm run build:renderer

      - name: Package Electron app
        run: npm run package

      - name: Make universal binary
        run: npm run make

      - name: Upload universal binary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-universal-binary
          path: out/make/* # Adjust this path to match where Electron Forge outputs the binary
